name: Generate Platform Distribution Pie Chart

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at noon
  workflow_dispatch:

jobs:
  generate-pie-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Generate Mermaid.js Pie Chart in README
        run: |
          python generate_pie_chart_readme.py

      - name: Commit README file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README with Platform Distribution pie chart"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
